disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Michelle Nghi Nguyen"




[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "pinklogo.png"
secondaryLogo = "whitelogo.png"
description = "Michelle Nghi Nguyen - International Economics - UEL - SGH Warsaw"
author = { image = "pnghiface.jpeg" }


[author]
